[colors.bright]
black = "#444b6a"
blue = "#7da6ff"
cyan = "#0db9d7"
green = "#b9f27c"
magenta = "#bb9af7"
red = "#ff7a93"
white = "#acb0d0"
yellow = "#ff9e64"

[colors.normal]
black = "#32344a"
blue = "#7aa2f7"
cyan = "#449dab"
green = "#9ece6a"
magenta = "#ad8ee6"
red = "#f7768e"
white = "#9699a8"
yellow = "#e0af68"

[colors.primary]
background = "#24283b"
foreground = "#a9b1d6"

[font]
size = 10.0

[font.bold]
family = "JetBrainsMono"
style = "Bold"

[font.normal]
family = "JetBrainsMono"
style = "Medium"

[scrolling]
history = 100

[window]
opacity = 0.97

[window.padding]
x = 15
y = 15
